# Generated by Django 4.1 on 2022-09-02 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0002_choice_enrollment_learner_lesson_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='is_registered',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='learner',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
