# Generated by Django 4.1 on 2022-09-03 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0003_learner_is_registered_learner_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='learner',
            name='email',
            field=models.CharField(max_length=40),
        ),
    ]
