# Generated by Django 4.1 on 2022-09-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0004_alter_instructor_email_alter_learner_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learner',
            name='id',
        ),
        migrations.AlterField(
            model_name='learner',
            name='email',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
    ]
