# Generated by Django 4.1 on 2022-09-03 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0006_alter_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='learner',
            name='is_logged_in',
            field=models.BooleanField(default=False),
        ),
    ]
