# Generated by Django 4.1 on 2022-09-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0007_learner_is_logged_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video',
            field=models.FileField(default='', upload_to='videos/'),
        ),
    ]
