# Generated by Django 4.1 on 2022-09-04 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0008_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instructor',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='learner',
            name='email',
            field=models.EmailField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='learner',
            name='password',
            field=models.CharField(max_length=32),
        ),
    ]
