# Generated by Django 4.1 on 2022-09-12 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0010_course_selected'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
