# Generated by Django 4.1 on 2022-09-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0014_lesson_selected_alter_question_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='grade',
            field=models.IntegerField(default=0),
        ),
    ]
