# Generated by Django 4.1 on 2022-09-20 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0015_lesson_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='link',
            field=models.URLField(blank=True, max_length=3000, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, default='', null=True, upload_to='videos/'),
        ),
    ]
