# Generated by Django 4.1 on 2022-09-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0018_question_question_content_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='question_content_images',
            new_name='question_content_image',
        ),
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.CharField(blank=True, default='', max_length=1000, null=True),
        ),
    ]
