# Generated by Django 4.1 on 2022-09-21 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CourseApp', '0019_rename_question_content_images_question_question_content_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question_content',
            field=models.TextField(blank=True, default='', max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_content_image',
            field=models.FileField(blank=True, default='', null=True, upload_to='question_images/'),
        ),
    ]
